apiVersion: apps/v1
kind: Deployment
metadata:
  name: cancel
  labels:
    app: cancel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cancel
  template:
    metadata:
      labels:
        app: cancel
    spec:
      containers:
        - name: cancel
          image: username/cancel:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5